theme = 'cyberscape'
baseURL = 'https://hackermymusic.com'
languageCode = 'en-us'
title = 'Hacker My Music Homepage'


# Enable this for Tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true